"""empty message

Revision ID: 35db086cf82b
Revises: 
Create Date: 2019-09-04 09:14:24.438267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35db086cf82b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genders',
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('gender_id', name=op.f('pk_genders'))
    )
    op.create_table('industries',
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('industry_id', name=op.f('pk_industries'))
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_projects'))
    )
    op.create_table('states',
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('state_id', name=op.f('pk_states'))
    )
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.industry_id'], name=op.f('fk_companies_industry_id_industries')),
    sa.ForeignKeyConstraint(['state_id'], ['states.state_id'], name=op.f('fk_companies_state_id_states')),
    sa.PrimaryKeyConstraint('company_id', name=op.f('pk_companies'))
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_employees_company_id_companies')),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.gender_id'], name=op.f('fk_employees_gender_id_genders')),
    sa.PrimaryKeyConstraint('employee_id', name=op.f('pk_employees'))
    )
    op.create_table('employee_has_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('fk_employee_has_project_employee_id_employees')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_employee_has_project_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_has_project'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_has_project')
    op.drop_table('employees')
    op.drop_table('companies')
    op.drop_table('states')
    op.drop_table('projects')
    op.drop_table('industries')
    op.drop_table('genders')
    # ### end Alembic commands ###
